<?php

namespace AppBundle\Repository;

/**
 * Car_conditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Car_conditionRepository extends \Doctrine\ORM\EntityRepository
{
}
